apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: restaurant
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: restaurant_db
  MYSQL_USER: root
  MYSQL_PASSWORD: password